version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10

dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
  pre:
    - sudo npm install -g now

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/awsome-blog # directory where steps will run
    executor: node-executor
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - run:
          name: pwd-now
          command: |
            ls
            pwd
  deploy:
    working_directory: ~/awsome-blog # directory where steps will run
    executor: node-executor
    steps:
      - run:
          name: add-now
          command: sudo npm install -g now
      - run:
          name: deploy-now
          command: |
            URL=$(now -t ${NOW_TOKEN})
            now -t ${NOW_TOKEN} alias ${URL} https://islam-farg.ml/
  branch_deploy:
    working_directory: ~/awsome-blog # directory where steps will run
    executor: node-executor
    steps:
      - run:
          name: add-now
          command: sudo npm install -g now
      - run:
          name: deploy-now
          command: |
            cd /home/circleci/awsome-blog
            pwd
            ls 
            echo __${NOW_TOKEN}__
            URL=$(
              now -t ${NOW_TOKEN}
            )
            now -t ${NOW_TOKEN} alias ${URL} https://${CIRCLE_BRANCH}.islam-farg.ml/
            echo __${URL}__
            echo https://${CIRCLE_BRANCH}.islam-farg.ml/

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - build
      - can_deploy:
          type: approval
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - can_deploy_branch:
          type: approval
          filters:
            branches:
              ignore:
                - master
          requires:
            - build
      - deploy:
          requires:
            - can_deploy
      - branch_deploy:
          requires:
            - can_deploy_branch
